name: CI

on: [push, pull_request]

jobs:
  crates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly]
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: ${{ matrix.target }}
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -p axhal_cpu -p axhal_plat --target ${{ matrix.target }} --all-features
    - name: Build
      run: cargo build -p axhal_cpu -p axhal_plat --target ${{ matrix.target }} --all-features
    - name: Unit test
      if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
      run: cargo test -p axhal_cpu -p axhal_plat --all-features -- --nocapture

  cli:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src, clippy
    - name: Clippy
      run: cargo clippy -p axplat-cli
    - name: Build
      run: cargo build -p axplat-cli

  platforms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: axplat-x86-pc
            target: x86_64-unknown-none
          - name: axplat-aarch64-common
            target: aarch64-unknown-none
          - name: axplat-aarch64-qemu-virt
            target: aarch64-unknown-none
          - name: axplat-aarch64-raspi
            target: aarch64-unknown-none
          - name: axplat-custom
            target: x86_64-unknown-none
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src, clippy
        targets: ${{ matrix.platform.target }}
    - name: Clippy
      run: cargo clippy --target ${{ matrix.platform.target }} -p ${{ matrix.platform.name }} --all-features
    - name: Build
      run: cargo build --target ${{ matrix.platform.target }} -p ${{ matrix.platform.name }} --all-features

  doc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
      RUSTDOCFLAGS: -Zunstable-options --enable-index-page -D rustdoc::broken_intra_doc_links -D missing-docs
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build docs
      continue-on-error: ${{ github.ref != env.default-branch && github.event_name != 'pull_request' }}
      run: |
        cargo doc --no-deps --all-features --workspace --exclude "axplat-*"
        cargo doc --no-deps --all-features -p axplat-aarch64-common
    - name: Deploy to Github Pages
      if: ${{ github.ref == env.default-branch }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: true
        branch: gh-pages
        folder: target/doc
